apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  namespace: default
  labels:
    io.kompose.service: apache
  name: apache
spec:
  type: ClusterIP
  ports:
  - name: apache
    port: 8080
    targetPort: 80
  externalIPs:
  - 192.168.1.176
  selector:
    io.kompose.service: apache
