apiVersion: v1
kind: PersistentVolume
metadata:
  name: fastapi-claim0
spec:
  capacity:
    storage: 1000Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/falcowalko/milestone2-files/app
