apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-claim0
spec:
  capacity:
    storage: 5000Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/vagrant/milestone2-files/database
