apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  type: ClusterIP
  ports:
  - name: "postgresql"
    port: 5432
    targetPort: 5432
  externalIPs:
  - 192.168.1.176
  selector:
    io.kompose.service: postgres
